server:
  port: 8762

# A prefix that can added to beginning of all requests.
#zuul.prefix=/api

# Disable accessing services using service name (i.e. order-service).
# They should be only accessed through the path defined below.
# Link: https://stackoverflow.com/questions/46317388/zuul-service-name-exposed-instead-of-route-path-only
zuul:
  ignored-services: '*'
  routes:
    product-service:
      path: /product/**
      service-id: PRODUCT-SERVICE
    auth-service:
      path: /auth/**
      service-id: AUTH-SERVICE
      # By default, all requests to order service for example will start with: "/order/"
      # What will be sent to the order service is what comes after the path defined,
      # So, if request is "/order/view/1", order service will get "/view/1".
      # In case of auth, we need to pass the "/auth/" in the path to auth service. So, set strip-prefix to false
      strip-prefix: false
      # Exclude authorization from sensitive headers
      sensitive-headers: Cookie,Set-Cookie
## Configuring info endpoint
info:
  app:
    name: Gate way server
    description: This server role as a gateway in microservice
    version: 1.0.0


# Map paths to order services
#zuul.routes.order-service.path=/order/**
#zuul.routes.order-service.service-id=ORDER-SERVICE